<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4IQHI62" name="Wooplr_Challenge Testscripts - Sanity" tests="52" failures="34" timestamp="15 Dec 2016 14:20:57 GMT" time="91.894" errors="0">
  <testcase name="challengeFlowTest" time="5.684" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="ListAdminReviews is giving response as null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: ListAdminReviews is giving response as null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeTestPlan.challengeFlowTest(ChallengeTestPlan.java:245)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- challengeFlowTest -->
  <testcase name="challengeFlowTest" time="5.297" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="ListAdminReviews is giving response as null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: ListAdminReviews is giving response as null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeTestPlan.challengeFlowTest(ChallengeTestPlan.java:245)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- challengeFlowTest -->
  <testcase name="createChallenge" time="1.38" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.143" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.028" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.05" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="0.959" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.287" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.027" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.026" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="0.96" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.0" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.171" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.048" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="0.957" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="0.968" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="createChallenge" time="1.755" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="deleteChallenge" time="1.477" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Showing wrong acknowledgement msg expected [null] but found [No challenge exist for given Id]">
      <![CDATA[java.lang.AssertionError: Showing wrong acknowledgement msg expected [null] but found [No challenge exist for given Id]
	at com.wooplr.challenge.test.ChallengeTestPlan.deleteChallenge(ChallengeTestPlan.java:106)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- deleteChallenge -->
  <testcase name="deleteChallenge" time="1.622" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Showing wrong acknowledgement msg expected [null] but found [No challenge exist for given Id]">
      <![CDATA[java.lang.AssertionError: Showing wrong acknowledgement msg expected [null] but found [No challenge exist for given Id]
	at com.wooplr.challenge.test.ChallengeTestPlan.deleteChallenge(ChallengeTestPlan.java:106)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- deleteChallenge -->
  <testcase name="getChallenge" time="1.526" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="listChallenge" time="7.387" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
  <testcase name="listChallengeByAction" time="0.951" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Showing wrong entries in ListChallenges by PARTICIPATED expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Showing wrong entries in ListChallenges by PARTICIPATED expected [true] but found [false]
	at com.wooplr.challenge.test.ChallengeHelper.validateTimeStamp(ChallengeHelper.java:112)
	at com.wooplr.challenge.test.ChallengeTestPlan.listChallengeByAction(ChallengeTestPlan.java:217)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- listChallengeByAction -->
  <testcase name="listChallengeByAction" time="1.361" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Showing wrong entries in ListChallenges by PARTICIPATED expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Showing wrong entries in ListChallenges by PARTICIPATED expected [true] but found [false]
	at com.wooplr.challenge.test.ChallengeHelper.validateTimeStamp(ChallengeHelper.java:112)
	at com.wooplr.challenge.test.ChallengeTestPlan.listChallengeByAction(ChallengeTestPlan.java:217)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- listChallengeByAction -->
  <testcase name="listChallengeByAction" time="1.395" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Showing wrong entries in ListChallenges by CURRENTGOING expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Showing wrong entries in ListChallenges by CURRENTGOING expected [true] but found [false]
	at com.wooplr.challenge.test.ChallengeHelper.validateTimeStamp(ChallengeHelper.java:116)
	at com.wooplr.challenge.test.ChallengeTestPlan.listChallengeByAction(ChallengeTestPlan.java:217)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- listChallengeByAction -->
  <testcase name="listChallengeByAction" time="1.253" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Showing wrong entries in ListChallenges by CURRENTGOING expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Showing wrong entries in ListChallenges by CURRENTGOING expected [true] but found [false]
	at com.wooplr.challenge.test.ChallengeHelper.validateTimeStamp(ChallengeHelper.java:116)
	at com.wooplr.challenge.test.ChallengeTestPlan.listChallengeByAction(ChallengeTestPlan.java:217)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- listChallengeByAction -->
  <testcase name="listChallengeByAction" time="1.278" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Created a challenge as PARTICIPATED, but it is not listed,, challengeId: 5736673905213440 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Created a challenge as PARTICIPATED, but it is not listed,, challengeId: 5736673905213440 expected [true] but found [false]
	at com.wooplr.challenge.test.ChallengeTestPlan.listChallengeByAction(ChallengeTestPlan.java:219)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- listChallengeByAction -->
  <testcase name="listChallengeByAction" time="0.909" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Created a challenge as PARTICIPATED, but it is not listed,, challengeId: 6473914906574848 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Created a challenge as PARTICIPATED, but it is not listed,, challengeId: 6473914906574848 expected [true] but found [false]
	at com.wooplr.challenge.test.ChallengeTestPlan.listChallengeByAction(ChallengeTestPlan.java:219)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- listChallengeByAction -->
  <testcase name="makeChallengeLive" time="2.003" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.wooplr.challenge.test.ChallengeTestPlan.makeChallengeLive(ChallengeTestPlan.java:123)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- makeChallengeLive -->
  <testcase name="makeChallengeLive" time="2.343" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.wooplr.challenge.test.ChallengeTestPlan.makeChallengeLive(ChallengeTestPlan.java:123)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- makeChallengeLive -->
  <testcase name="makeChallengeLive" time="1.867" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.wooplr.challenge.test.ChallengeTestPlan.makeChallengeLive(ChallengeTestPlan.java:123)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- makeChallengeLive -->
  <testcase name="makeChallengeLive" time="3.625" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.wooplr.challenge.test.ChallengeTestPlan.makeChallengeLive(ChallengeTestPlan.java:123)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- makeChallengeLive -->
  <testcase name="updateChallenge" time="1.619" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.449" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.325" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="3.324" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.33" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.224" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.255" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.306" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.314" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.655" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.651" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.37" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.489" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.273" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="3.514" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.691" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.648" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.611" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.539" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="updateChallenge" time="1.441" classname="com.wooplr.challenge.test.ChallengeTestPlan">
    <failure type="java.lang.AssertionError" message="Response body is coming null !! expected object to not be null">
      <![CDATA[java.lang.AssertionError: Response body is coming null !! expected object to not be null
	at com.wooplr.challenge.test.ChallengeHelper.validatechallenge(ChallengeHelper.java:19)
	at com.wooplr.challenge.test.ChallengeTestPlan.updateChallenge(ChallengeTestPlan.java:155)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- updateChallenge -->
  <testcase name="validateListChallenge" time="1.228" classname="com.wooplr.challenge.test.ChallengeTestPlan"/>
</testsuite> <!-- Wooplr_Challenge Testscripts - Sanity -->
